# Generated by Django 6.0.4 on 2026-07-23 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_deactivation_reason'),
        ('attendance', '0004_scheduletype'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='schedule_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='attendance.scheduletype'),
        ),
    ]
