# Generated by Django 6.0.4 on 2026-07-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_department_schedule_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Număr marcă'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('director', 'Director'), ('manager', 'Manager'), ('employee', 'Angajat')], default='employee', max_length=20),
        ),
    ]
