# Generated by Django 6.0.4 on 2026-07-24 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_employee_number_alter_user_role'),
        ('attendance', '0006_notification_code_notification_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='schedule_type',
            field=models.ForeignKey(blank=True, help_text='Program individual — suprascrie programul departamentului doar pentru acest angajat.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individual_users', to='attendance.scheduletype'),
        ),
    ]
