# Generated by Django 6.0.4 on 2026-07-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontajentry',
            name='leave_from_request',
            field=models.BooleanField(default=False),
        ),
    ]
