# Generated by Django 6.0.4 on 2026-07-23 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_department_schedule_type'),
        ('reports', '0002_pontajentry_leave_from_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pontajsheet',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pontajsheet',
            name='user',
            field=models.ForeignKey(blank=True, help_text="Set instead of department for a self-service personal sheet (e.g. the director's own).", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_pontaj_sheets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pontajsheet',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pontaj_sheets', to='accounts.department'),
        ),
        migrations.AddConstraint(
            model_name='pontajsheet',
            constraint=models.UniqueConstraint(condition=models.Q(('department__isnull', False)), fields=('department', 'year', 'month'), name='uniq_department_pontaj_sheet'),
        ),
        migrations.AddConstraint(
            model_name='pontajsheet',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'year', 'month'), name='uniq_personal_pontaj_sheet'),
        ),
    ]
