# Generated by Django 6.0.4 on 2026-07-23 06:22

from decimal import Decimal
from django.db import migrations, models


def seed_normal_schedule(apps, schema_editor):
    ScheduleType = apps.get_model('attendance', 'ScheduleType')
    ScheduleType.objects.get_or_create(
        name='Normal (09:00-17:00)',
        defaults={
            'start_time': '09:00',
            'end_time': '17:00',
            'break_minutes': 60,
            'pontaj_hours': Decimal('8.00'),
        },
    )


def remove_normal_schedule(apps, schema_editor):
    ScheduleType = apps.get_model('attendance', 'ScheduleType')
    ScheduleType.objects.filter(name='Normal (09:00-17:00)').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_overtimerequest_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('break_minutes', models.PositiveIntegerField(default=60)),
                ('pontaj_hours', models.DecimalField(decimal_places=2, default=Decimal('8.00'), help_text='Ore fixe de pontaj/tichete de masă per zi lucrată, indiferent de orele reale.', max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Schedule Type',
                'verbose_name_plural': 'Schedule Types',
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(seed_normal_schedule, remove_normal_schedule),
    ]
